version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: com.google.protobuf:protobuf-java-util
        update-types:
          - version-update:semver-major
      - dependency-name: com.google.protobuf:protoc
        update-types:
          - version-update:semver-major
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
      - OptimumCode
    labels:
      - dependencies
    schedule:
      interval: daily