version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
    labels:
      - dependencies
    schedule:
      interval: daily
    ignore:
      - dependency-name: com.google.protobuf:protobuf-java-util
        update-types:
          - version-update:semver-major
      - dependency-name: com.google.protobuf:protoc
        update-types:
          - version-update:semver-major
      - dependency-name: org.jetbrains.kotlin:kotlin-bom
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    directory: /
    reviewers:
      - Nikita-Smirnov-Exactpro
    labels:
      - dependencies
    schedule:
      interval: daily