name: Build and publish jar to sonatype snapshot repository

on:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java-dev.yml@main
    with:
      build-target: 'Sonatype'
    secrets:
      sonatypeUsername: ${{ secrets.CENTRAL_SONATYPE_COM_USERNAME }}
      sonatypePassword: ${{ secrets.CENTRAL_SONATYPE_COM_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
      cisa-domain: ${{ secrets.CISA_DOMAIN }}
      cisa-user: ${{ secrets.CISA_USER }}
      cisa-password: ${{ secrets.CISA_PWD }}